# Generated by Django 5.0.2 on 2024-12-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_remove_lessonmaterial_lesson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='initial_prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
