version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  worker:
    build: .
    env_file:
      - .env
    volumes:
      - ./backend:/app
    command: python worker.py
    depends_on:
      - temporal
      - redis
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    env_file:
      - .env
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
      - REDISINSIGHT_DEFAULT_PASSWORD=${REDIS_PASSWORD}

  temporal:
    image: temporalio/auto-setup:1.22.3
    ports:
      - "7233:7233"
      - "8088:8088"
    volumes:
      - temporal_data:/etc/temporal/config
      - ./backend/config/dynamicconfig:/etc/temporal/config/dynamicconfig
    env_file:
      - .env
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PWD=${POSTGRES_PASSWORD}
      - POSTGRES_SEEDS=db
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - TEMPORAL_NAMESPACE=${TEMPORAL_NAMESPACE}
      - TEMPORAL_HOST=${TEMPORAL_HOST}
      - TEMPORAL_TASK_QUEUE=${TEMPORAL_TASK_QUEUE}
      - TEMPORAL_SERVER_URL=${TEMPORAL_SERVER_URL}
    depends_on:
      - db
      - redis

  temporal-ui:
    image: temporalio/ui:2.21.3
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:8080
    depends_on:
      - temporal

volumes:
  postgres_data:
  redis_data:
  temporal_data: